

# SYSTEM CONFIGS
MODE = 0    # gpu: 0    cpu: 1
GPU_ID = 0

# TRAIN CONFIGS
IMAGE_BATCH_SIZE = 1
IMAGE_SHAPE = [224, 224]
DATASET_PATH = None
ANNO_PATH = None
LABEL_PATH = None
NUM_CLS = 3     # Exclude background

BACKBONE = 'resnext50'
FEATURE_STRIDE = 16

MODEL_SAVE_PATH = './logs/model'
SAVE_MODEL_ITER = 100
SAVE_MODEL_MAXIMUM_ITERS = 10000

SUMMARY_PATH = './logs'
REFRESH_LOGS_ITERS = 10

ADD_GT_BOX_TO_TRAIN = False

# ANCHOR CONFIGS
ANCHOR_BASE_SIZE = 16
ANCHOR_SCALE = [8, 16, 32]
ANCHOR_RATE = [0.5, 1.0, 2.0]
ANCHOR_NUM = len(ANCHOR_SCALE) * len(ANCHOR_RATE)
ROI_SCALE_FACTORS = [5., 5., 10., 10.]

# RPN_CONFIGS
RPN_KERNEL_SIZE = 3
RPN_IOU_POSITIVE_THRESHOLD = 0.7
RPN_IOU_NEGATIVE_THRESHOLD = 0.3
RPN_FOREGROUND_FRACTION = 0.5

RPN_PROPOSAL_MAX_TRAIN = 2000
RPN_PROPOSAL_MAX_TEST = 300

RPN_MINIBATCH_SIZE = 256
RPN_NMS_IOU_THRESHOLD = 0.7

RPN_BN_DECACY = 0.995
RPN_BN_EPS = 0.0001
RPN_WEIGHTS_L2_PENALITY_FACTOR = 0.0005


# FASTER_RCNN_CONFIGS
FASTER_RCNN_NMS_IOU_THRESHOLD = 0.3
FASTER_RCNN_IOU_POSITIVE_THRESHOLD = 0.5
FASTER_RCNN_IOU_NEGATIVE_THRESHOLD = 0.0
FASTER_RCNN_MINIBATCH_SIZE = 256
FASTER_RCNN_POSITIVE_RATE = 0.25



